### PR TITLE
Updates to match recent changes to sPyNNaker

### PR DESCRIPTION
**Pull request by andrewgait**
As with PyNN8Examples update...

... though I do think there's something now wrong with the Sudoku visualiser, so I'm going to look at that as well separate to this.

### CODE REVIEW

**Comment by andrewgait** [comment]
I ought to have clarified here too - sudoku seems to have problems running at the default number of neurons per core; I reduced it to 200 which made it work again, but this behaviour could probably do with being diagnosed as well.

**Comment by rowleya** [comment]
It always used to have timer overruns etc.  If 200 neurons per core sorts this out, I am happy to leave it that way...

**Comment by andrewgait** [comment]
It warns of some timer overruns at 200 neurons per core now, though it does run to completion.  It actually fails at 255 at the moment because some of the cores fail to complete running within the allotted timeout (5 seconds, I think?) after the end of the run.

**Comment by rowleya** [comment]
Hmm OK, that could do with a look!

**Pull request merged**
