### PR TITLE
Spinnaker start

### PR DESCRIPTION
**Pull request by rowleya**
Time to get this into master?

### CODE REVIEW

**Comment by Christian-B** [comment]
Any reason not to add these to Integrations tests?

Specificaly script_builder.py

**Review by Christian-B — CHANGES_REQUESTED** [review]
test!

**Comment by rowleya** [comment]
All of these applications open a GUI.  It would be good at some point to separate the operation from the GUI, but that hasn't been done so far.  Issue #53 created to at least keep track of this.

**Comment by Christian-B** [comment]
suduko
spinn_utilities.exceptions.ConfigException: Unexpected None for section='Database' option='wait_on_confirmation_timeout'

**Comment by rowleya** [comment]
These should be working now...

**Pull request merged**
